language: c++
compiler: clang
os: linux
sudo: false

addons:
    apt:
      packages:
        - cmake
      sources:
        - kalakris-cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target test_lexer
