language: cpp
compiler: clang


before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update -q
  - sudo apt-get install --only-upgrade cmake -y

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target test_lexer
